services:
  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
      --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
